name: sdk-py-location-transform
title: HD Vision Helper
version: 1.0.0
summary: Controls the HD Vision Camera and AI and returns Robot Space locations
description: |
  This app is used to locate the Ctrlx letters relative to the location on the board.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  locationtransform:
    command: bin/main.py
    plugs:
      - network-bind
      - active-solution
    slots:
      - package-assets
      - package-run
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  locationtransform:
    plugin: python
    source: .
    stage-packages:
      - ctrlx-datalayer

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/

 
  bfbs:
    plugin: dump
    source: ./bfbs

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}

  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${CRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*
